### ISSUE TITLE
classifyT1BC: Error in UseMethod("tbl_vars")

### ISSUE THREAD

**Issue by ladyjkalx** [csgroen/classifyT1BC#1]
Hi,
When I tried to run the classifyT1BC classification function on an expression data matrix (formatted as specified in the function), I encountered the following error:
> classifyT1BC(l2expr.m, id_type = "ensembl_id")
Error in UseMethod("tbl_vars") : 
  no applicable method for 'tbl_vars' applied to an object of class "function"

I'm able to run similar packages such as the MIBC consensus classifier (github: consensusMIBC) and bladder cancer subtyping (github: BLCAsubtyping) classifiers on the same object without problem.

Here is my session info:
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] classifyT1BC_0.1.0 tibble_2.1.3       tidyr_1.0.0        magrittr_1.5       dplyr_0.8.3       

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3       crayon_1.3.4     assertthat_0.2.1 R6_2.4.1         lifecycle_0.2.0  pillar_1.4.3     rlang_0.4.5      vctrs_0.2.4      glue_1.3.1       purrr_0.3.3     
[11] compiler_3.6.3   pkgconfig_2.0.3  tidyselect_0.2.5

**Comment by csgroen** [comment]
Hi!
Can you tell me the class of `l2exp.m` ? Could you
`dput(head(l2exp.m))`
and post the results here just so I can have a debugging dataset?

**Comment by ladyjkalx** [comment]
here you go, thanks!

> class(l2exp.m)
[1] "matrix"
> dput(head(l2exp.m[,1:50]))
structure(c(64.6141, 0.0309569, 77.1156, 19.3198, 2.8242, 5.01231, 
103.595, 0, 21.1716, 6.42829, 0.985155, 1.7991, 43.9209, 0, 39.0314, 
16.7741, 7.60256, 1.78584, 61.7301, 0, 54.5105, 11.3189, 2.62145, 
5.86677, 21.0246, 0, 19.7974, 6.10313, 3.94179, 5.61609, 81.8369, 
0, 63.4333, 11.2189, 2.21128, 4.40688, 224.443, 0, 60.4163, 16.7419, 
10.7338, 0.678999, 216.03, 0.231049, 44.9131, 10.6224, 5.30344, 
6.57067, 47.5535, 0.00408979, 24.7684, 6.85936, 2.5734, 4.42437, 
112.988, 0.00338745, 45.3873, 9.16038, 4.86893, 1.63539, 180.706, 
0.118661, 63.3146, 9.63614, 6.79095, 2.34632, 72.5529, 0, 36.1409, 
7.15217, 1.6705, 2.02242, 63.1834, 0.0042749, 29.517, 7.69375, 
2.92622, 1.57242, 131.6, 0, 88.1431, 12.289, 3.65204, 1.4793, 
146.792, 0.0453255, 55.4956, 11.2897, 3.57214, 5.15596, 124.659, 
0, 56.7063, 12.851, 3.77427, 1.25124, 82.7601, 0, 39.0877, 8.33471, 
3.13968, 2.27517, 66.6316, 0, 40.2802, 8.93363, 3.60525, 2.70933, 
76.6639, 0, 59.5631, 11.2767, 2.27016, 5.41936, 86.2059, 0.00287172, 
32.708, 6.80632, 7.05972, 0.124399, 84.0451, 0, 92.4134, 18.4391, 
16.8994, 5.92012, 55.1784, 0, 27.4335, 6.09443, 3.20428, 2.36469, 
33.2593, 0, 20.7122, 4.49672, 2.07773, 6.03676, 110.45, 0.132346, 
52.7603, 10.1101, 3.24741, 4.25462, 77.012, 0.164495, 46.1327, 
8.71846, 2.75996, 2.17122, 70.7322, 0.00308423, 45.6045, 9.51122, 
4.5681, 2.15349, 100.951, 0, 40.5519, 8.90435, 5.84537, 3.27196, 
68.638, 0.124626, 41.6549, 7.43026, 3.22191, 2.79904, 33.7799, 
0, 42.7281, 9.13796, 4.33629, 0.657436, 75.7072, 0, 78.2209, 
15.0161, 53.2452, 0.857962, 84.6318, 0.00861278, 64.1141, 8.86496, 
5.95007, 0.811278, 75.0134, 0, 43.6537, 7.97262, 4.54255, 1.47138, 
238.152, 0, 41.9455, 7.7451, 22.5209, 0.114892, 174.69, 0.0118051, 
48.3045, 12.3705, 11.3051, 0.266597, 84.5086, 0, 45.8013, 6.0939, 
2.71025, 1.25302, 234.667, 0, 39.0091, 3.7379, 6.22261, 0.803481, 
59.7307, 0, 40.0977, 12.2134, 1.63267, 0.0625602, 111.951, 0, 
62.3858, 9.95063, 3.15228, 9.72282, 84.7507, 0, 54.518, 10.238, 
2.79522, 2.52766, 69.847, 0.00286929, 93.1342, 11.3924, 10.7813, 
2.15472, 116.587, 0, 43.5559, 7.27824, 15.2787, 1.74386, 91.5003, 
0, 45.4525, 4.18156, 8.25778, 0.106921, 71.7104, 0, 56.8903, 
16.7971, 20.8452, 1.90004, 50.1896, 0, 32.1233, 10.0246, 19.0412, 
2.3013, 60.8678, 0.012964, 41.6929, 9.14442, 12.5316, 0.710018, 
83.7536, 0.00334597, 79.4982, 10.1743, 3.50646, 1.14277, 91.8173, 
0, 53.9789, 9.43261, 6.04025, 0.83533, 56.7148, 0.012266, 63.8343, 
8.77772, 3.23552, 1.26751, 117.949, 0.00377881, 56.6596, 9.38803, 
6.44255, 1.99622, 44.1487, 0, 71.8446, 10.4386, 3.90188, 1.26988
), .Dim = c(6L, 50L), .Dimnames = list(c("ENSG00000000003", "ENSG00000000005", 
"ENSG00000000419", "ENSG00000000457", "ENSG00000000460", "ENSG00000000938"
), c("U0001", "U0002", "U0006", "U0007", "U0010", "U0011", "U0012", 
"U0013", "U0015", "U0018", "U0023", "U0024", "U0026", "U0027", 
"U0028", "U0032", "U0035", "U0036", "U0037", "U0038", "U0039", 
"U0041", "U0042", "U0045", "U0046", "U0048", "U0053", "U0054", 
"U0057", "U0059", "U0060", "U0062", "U0064", "U0067", "U0069", 
"U0071", "U0072", "U0073", "U0074", "U0076", "U0077", "U0078", 
"U0080", "U0083", "U0086", "U0087", "U0088", "U0089", "U0090", 
"U0091")))

**Comment by csgroen** [comment]
Thanks for catching this! There was a bug in the conversion from ensembl_id to symbol before running the model prediction.

Please install the new version (make sure you have 0.1.2) and let me know if you have any problems so I can close the issue.

**Comment by ladyjkalx** [comment]
Works great now. Thanks for the quick response!  Nice paper..
