### ISSUE TITLE
Strange results

### ISSUE THREAD

**Issue by kosta-blackshow** [csgroen/classifyT1BC#2]
I've performed prediction on normalized, log-scaled data from publically available datasets GSE128959 and GSE32894, separately.  
Classificator define all samples as '2' class.

**Comment by csgroen** [comment]
Hi Kosta, thanks for reaching out.

I checked the two datasets in question on GEO and they both assessed gene expression using array technologies. The reason we specify to use 'RNA-seq results' is that when we were building the model for this classifier, I found that I couldn't get a model that was as accurate in our train/test/validation cohorts and also able to classify microarray samples correctly. 

I can send you a few other model types that ended up not being used (were less accurate overall) to see if they are able to classify microarray samples.

**Comment by csgroen** [comment]
Hi @kosta-blackshow : it's done. I added one of the NSC models we built which was a candidate. It's less accurate (85%), but more robust to data space differences and works with microarray data.

Make sure you have v0.2.0 and re-run the function with `data_type = "array"`. Please let me know if that solves the issue so I can close.

**Comment by kosta-blackshow** [comment]
Hi, Clarice! 
My bad, I didn't see that algorithm is only for RNA-seq. 
Thanks for one more model for arrays! May be it's less accurate, but it definitely works!
